### ISSUE TITLE
[Q] Compatible RT-AX88U?

### ISSUE THREAD

**Issue by chris777c** [lunarok/jeedom_asuswrt#2]
Bonjour,

Est-ce que le plugin ASUSWRT est compatbile avec RT-AX88U version firmware [3.0.0.4.384_7968] ?

**Comment by lunarok** [comment]
Les issues Github ne sont pas un moyen de poser des questions ou du support.
Merci de poser la question via le forum.

**Comment by chris777c** [comment]
Bonjour,
en effet mais n'ayant pas eu de réponse j'ai tenté le coup : https://community.jeedom.com/t/asuswrt-compatible-rt-ax88u/17897
